[buildPlans.IosevkaCustom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.IosevkaCustom.variants]
inherits = "ss15"

[buildPlans.IosevkaCustom.ligations]
inherits = "dlig"
